#!/bin/bash - 
#===============================================================================
#
#          FILE: push.sh
# 
#         USAGE: ./push.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: liuxueyang (lxy), liuxueyang457@163.com
#  ORGANIZATION: Hunan University
#       CREATED: 04/11/2014 19:31
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error
git add --all 
git commit -m 'add or modify sth.'
git push origin master

